name: Deploy to EC2 CITI Machine
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: '${{ secrets.EC2_HOST }}'
          username: '${{ secrets.EC2_USER }}'
          key: '${{ secrets.EC2_SSH_PRIVATE_KEY }}'
          script: |
            cd /projects/ms-cotizate/
            git pull
            # Restart your application or run any other required commands
